"""empty message

Revision ID: 216c7dbe8b7c
Revises: 9eeea1a66cd1
Create Date: 2023-07-28 15:01:21.252985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216c7dbe8b7c'
down_revision = '9eeea1a66cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=70), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
