"""empty message

Revision ID: 857a6091df45
Revises: e2b30b88e7bf
Create Date: 2023-08-01 15:31:53.000168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857a6091df45'
down_revision = 'e2b30b88e7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint('visits_city_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cities', ['city_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('visits_city_id_fkey', 'cities', ['city_id'], ['id'])

    # ### end Alembic commands ###
