"""empty message

Revision ID: bebff50a2d3d
Revises: f061ab68214b
Create Date: 2023-07-28 15:04:11.810158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebff50a2d3d'
down_revision = 'f061ab68214b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited', sa.Boolean(), server_default='false', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('visited')

    # ### end Alembic commands ###
